apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nkp-previews
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: evanshortiss
        repo: neon-kube-previews
        # Optional. Only create previews for a PR with the given label(s)
        # labels:
        #  - preview
      # Check the repository for PRs every 60 seconds
      requeueAfterSeconds: 60
  template:
    metadata:
      name: 'nkp-pr-{{number}}'
    spec:
      source:
        path: helm/
        repoURL: 'https://github.com/evanshortiss/neon-kube-previews'
        targetRevision: '{{head_sha}}'
        helm:
          valueFiles:
          - values.dev.yaml
          # The database.url value will be replaced by CI once it creates the
          # Neon preview branch. Replace ingress.domain with your desired
          # hostname. Previews use the following URL structure:
          # nkp-pr-{{number}}.{{ingress.domain}}
          values: >-
            {
              database: {
                url: "postgres://user:password@hostname/neondb"
              },
              deployment: {
                image: {
                  tag: {{head_sha}}
                }
              },
              ingress: {
                domain: "pr-{{number}}.nkp.ngrok.app"
              }
            }
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'nkp-pr-{{number}}'
