apiVersion: apps/v1
kind: Deployment
metadata:
  name: neon-kube-previews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neon-kube-previews
  template:
    metadata:
      labels:
        app: neon-kube-previews
    spec:
      containers:
      - name: neon-kube-previews
        image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: database_url
---
