apiVersion: v1
kind: Service
metadata:
  name: neon-kube-previews
spec:
  selector:
    app: neon-kube-previews
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.port }}
  type: ClusterIP
