
deployment:
  # More replicas in production vs dev
  replicaCount: 2
  port: 3000
  image:
    repository: docker.io/evanshortiss/neon-kube-previews
    pullPolicy: Always
    tag: latest
  resources:
    limits:
      # Burstable up to 1/2 core and 1/2 a gig
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

service:
  port: 80

ingress:
  domain: neon-kube-previews.ngrok.app
