
deployment:
  replicaCount: 2
  port: 3000
  image:
    repository: docker.io/evanshortiss/neon-kube-previews
    pullPolicy: Always
    tag: latest
  resources:
    limits:
      # Lower resources for development vs production
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

database: {}
service:
  port: 80
labels:
  app: neon-kube-previews
  environment: "development"
ingress: {}


