
deployment:
  # More replicas in production vs dev
  replicaCount: 2
  port: 3000
  image:
    repository: evanshortiss/neon-kube-previews
    pullPolicy: Always
    tag: 8fb8866310dbaad7c117c81b98cac99913b9e45e
  resources:
    limits:
      # Burstable up to 1/2 core and 1/2 a gig
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
service:
  port: 80
ingress:
  domain: neon-kube-previews.ngrok.app
