
deployment:
  replicaCount: 1
  port: 3000
  image:
    repository: docker.io/evanshortiss/neon-kube-previews
    pullPolicy: Always
    tag: latest
  resources:
    limits:
      # Lower resources for development vs production
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

service:
  port: 80

ingress: {}
