name: Deploy Production

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-container:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: elements-application/
        file: elements-application/Containerfile
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/neon-kube-previews:${{ github.sha }},${{ secrets.DOCKERHUB_USERNAME }}/neon-kube-previews:latest

  update-production-tag:
    needs: build-container
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install yq
      run: |
        sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.35.2/yq_linux_amd64 -o /usr/local/bin/yq
        sudo chmod +x /usr/local/bin/yq

    - name: Update values.yaml
      run: |
        'yq -i e ".deployment.image.repository = \"${{ secrets.DOCKERHUB_USERNAME }}/neon-kube-previews\"" helm/values.yaml'
        'yq -i e ".deployment.image.tag = \"${{ github.sha }}\"" helm/values.yaml'

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      id: cpr
      with:
        title: ${{ github.event.inputs.message }}
        branch: release-${{ github.sha }}
        commit-message: update backend image tag to ${{ github.sha }}

    - name: Check outputs
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
